#!/bin/bash
# this script is a modification of dmenu_run used
# to only update the dmenu cache
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
  cache=$cachedir/dmenu_run
else
  cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
fi

# Add prefix to cache file.
cache=$cache-$(echo "$PATH" |sha1sum |awk '{print $1}')

(
  IFS=:
  if [[ ! -f "$cache" ]] || stest -dqr -n "$cache" $PATH; then
    stest -flx $PATH | sort -u | tee "$cache"
  else
    cat "$cache"
  fi
)
